<?
use Bitrix\Main\Page\Asset;
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Депозиты | Депозиты и Векселя | КОРПОРАТИВНЫМ КЛИЕНТАМ | Трансстройбанк");
$APPLICATION->SetPageProperty("description", "АКБ «Трансстройбанк» (АО) предлагает юридическим лицам получить дополнительный доход, вложив свои денежные средства в один из существующих депозитов по выгодным условиям.");
$APPLICATION->SetPageProperty("keywords", "Депозиты АКБ «ТрансСтройБанк»");
$APPLICATION->SetTitle("Депозит «Бизнес-доход»");
Asset::getInstance()->addCss("/corporative-clients/razmeshchenie-sredstv/depozity/style.css");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"corporative-deposits",
	Array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array("",""),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		//"DETAIL_PROPERTY_CODE" => array("ADD_INFO_BANK","ADD_INFO_SELF","MAX_SUM","MIN_SUM","INTEREST_RATE","MAX_DATE"),
        "DETAIL_PROPERTY_CODE" => array("ADD_BLOCK_HEADER","ADD_MAIN_ATTRIBUTE","ADD_INTEREST_RATE","ADD_MIN_SUM","ADD_MAX_SUM","ADD_ADVANTAGES","ADD_ADVANTAGES_IMG","ADD_OPTION"),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"FILE_404" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "87",
		"IBLOCK_TYPE" => "corporative_clients",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array("",""),
		"LIST_PROPERTY_CODE" => array("ADD_BLOCK_HEADER","ADD_MAIN_ATTRIBUTE","ADD_INTEREST_RATE","ADD_MIN_SUM","ADD_MAX_SUM","ADD_ADVANTAGES","ADD_ADVANTAGES_IMG","ADD_OPTION"),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/corporative-clients/razmeshchenie-sredstv/depozity/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => Array("detail"=>"#ELEMENT_CODE#/","news"=>"","section"=>""),
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N"
	)
);?>

<?/*$APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "safes_reply",
    Array(
        "ACTIVE_DATE_FORMAT" => "d.m.Y",
        "ADD_SECTIONS_CHAIN" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CHECK_DATES" => "Y",
        "DETAIL_URL" => "",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_DATE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "FIELD_CODE" => array("", ""),
        "FILTER_NAME" => "",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => "86",
        "IBLOCK_TYPE" => "private_clients",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "INCLUDE_SUBSECTIONS" => "N",
        "MESSAGE_404" => "",
        "NEWS_COUNT" => "4",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => ".default",
        "PAGER_TITLE" => "Новости",
        "PARENT_SECTION" => "",
        "PARENT_SECTION_CODE" => "",
        "PREVIEW_TRUNCATE_LEN" => "",
        "PROPERTY_CODE" => array("FILE", ""),
        "SET_BROWSER_TITLE" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "N",
        "SET_META_KEYWORDS" => "N",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "N",
        "SHOW_404" => "N",
        "SORT_BY1" => "ACTIVE_FROM",
        "SORT_BY2" => "SORT",
        "SORT_ORDER1" => "DESC",
        "SORT_ORDER2" => "ASC",
        "STRICT_SECTION_CHECK" => "N"
    )
);*/?>
<?/*?>
<div class="popup-form" id="depositLegal">
	<?$APPLICATION->IncludeComponent(
		"webtu:feedback",
		"deposit_legal",
		Array(
			"ADMIN_EVENT" => "WEBTU_FEEDBACK_DEPOSIT_UL_ADMIN",
			"AJAX_MODE" => "Y",
			"AJAX_OPTION_ADDITIONAL" => "",
			"AJAX_OPTION_HISTORY" => "N",
			"AJAX_OPTION_JUMP" => "N",
			"AJAX_OPTION_STYLE" => "Y",
			"IBLOCK_ID" => "41",
			"EVENT_CALLBACK" => function($post){$post['RECOURSE']='Уважаемый(ая)';return$post;},
			"POST_CALLBACK" => function($post){{$post['NAME']=$post['FIRST_NAME'];}return$post;},
			"PROPERTIES" => array("COMPANY_NAME","PHONE","EMAIL","SUM","CURRENCY","DATE","DEPOSIT_NAME","INTEREST_RATE","MONTH_SUM","REPLENISHABLE","CUT","CAPITALIZATION","PAY"),
			"SITES" => array("s1"),
			"USER_EVENT" => "WEBTU_FEEDBACK_DEPOSIT_UL_USER",
			"DATE" => "",
			"DEPOSIT_NAME" => "",
			"INTEREST_RATE" => "",
			"MONTH_SUM" => "",
			"REPLENISHABLE" => "",
			"CUT" => "",
			"CAPITALIZATION" => "",
			"PAY" => "",
		)
	);?>
</div>
<?*/?>
<?
//Отображаем форму в футере
// \GarbageStorage::set('feedback', true);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
