<?
$aMenuLinks = Array(
    Array(
        "История",
        "/o-banke/istoriiya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Реквизиты",
        "/o-banke/rekvizity/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Руководство банка",
        "/o-banke/rukovodstvo-banka/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Раскрытие информации для регулятивных целей",
        "/o-banke/raskrytie-informatsii/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Финансовая отчетность",
        "/o-banke/finansovaya-otchetnost/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Карьера",
        "/o-banke/karera/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новости",
        "/o-banke/novosti/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Офисы и банкоматы",
        "/ofisy-i-bankomaty/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Статьи",
        "/o-banke/blog/",
        Array(),
        Array(),
        ""
    ),
);
?>
